name: release
on:
  push:
    branches:
      - 'main'
      - 'beta'
      - 'alpha'
  pull_request: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install deps
        run: yarn install
      - name: Check for regressions
        run: yarn lint
      - name: Check build health
        run: yarn build
      - name: Check for SSR compat
        run: node dist/index.cjs && node dist/index.js
      - name: Check NPM config
        run: npx publint@latest dist
  release:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'pmndrs/three-stdlib' && contains('refs/heads/main,refs/heads/beta,refs/heads/alpha',github.ref) && github.event_name == 'push' }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install deps
        # this runs a build script so there is no dedicated build
        run: yarn install
      - name: Check build health
        run: yarn build
      - name: 🚀 Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17
          extra_plugins: |
            @semantic-release/git
          branches: |
            [
              'main',
              {name: 'beta', prerelease: true},
              {name: 'alpha', prerelease: true}
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
